# Generated by Django 2.1.5 on 2020-12-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201207_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('comments', models.TextField(null=True)),
            ],
        ),
    ]
