# Generated by Django 2.1.5 on 2020-12-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201212_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='p_id',
            new_name='c_id',
        ),
    ]
