# Generated by Django 2.1.5 on 2020-12-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201212_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='Project_title',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='c_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='Project_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
