# Generated by Django 2.1.5 on 2020-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201213_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
