# Generated by Django 2.1.5 on 2020-12-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201206_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='Question_title',
        ),
        migrations.AddField(
            model_name='stud_ans',
            name='Question_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Question'),
        ),
    ]
