# Generated by Django 2.1.5 on 2020-12-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201213_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_ans',
            name='upvote',
        ),
    ]
