# Generated by Django 2.1.5 on 2020-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=120, null=True)),
                ('password', models.CharField(max_length=120)),
                ('uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('interests', models.TextField()),
                ('grade', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('projects', models.TextField(blank=True, max_length=300, null=True)),
                ('points', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
