# Generated by Django 2.1.5 on 2020-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_student', '0002_remove_student_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
