# Generated by Django 2.1.5 on 2020-12-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_student', '0003_auto_20201215_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='uid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
