# Generated by Django 2.1.5 on 2020-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_student', '0004_auto_20201215_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='student',
            name='email_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
